baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["github.com/dzello/reveal-hugo"]
[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
[markup.highlight]
codeFences = false
[params.reveal_hugo]
highlight_theme = "github"

[[params.reveal_hugo.plugins]]
# name must match the name by which the plugin is exported
name = "RevealMenu"
source = "plugins/menu/menu.js"
css = "plugins/menu/menu.css"