baseURL = 'http://cna.boxboat.io/'
languageCode = 'en-us'
title = 'Learning Go'
theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false

[params.reveal_hugo]
highlight_theme = "github"
theme = "white"
history = true
slide_number = true
transition = 'none'
transition_speed = 'fast'

[[params.reveal_hugo.plugins]]
# name must match the name by which the plugin is exported
name = "RevealMenu"
source = "plugins/menu/menu.js"
css = "plugins/menu/menu.css"
